### ISSUE TITLE
Joystick stucks

### ISSUE THREAD

**Issue by yurko7** [dondido/virtual-joystick#1]
virtual-joystick doesn't work in chromium-based browsers, it stucks on first move.

**Comment by dondido** [comment]
Hi there, are you able to replicate it on the demo page here: https://dondido.github.io/virtual-joystick/

**Comment by yurko7** [comment]
Hi, yep I can reproduce the bug in Chrome and Edge:
https://github.com/dondido/virtual-joystick/assets/14837626/e8a527c9-0a1c-4864-9cb0-1f5d1eae92b2

**Comment by dondido** [comment]
Hi, thank you for your video - I really appreciate that! What device are you using - I can't see any mouse cursor.

**Comment by yurko7** [comment]
It's a laptop with touchscreen, but behavior is the same with mouse and touch input.

**Comment by dondido** [comment]
Hey, thank you for spotting this. I've just made a little change - hopefully it's all sorted now. Just pull in the latest.

**Comment by yurko7** [comment]
Hey, thanks for quick fix, now it works perfectly well!
