### ISSUE TITLE
North is 0°

### ISSUE THREAD

**Issue by JTrotta** [dondido/virtual-joystick#2]
Nice work, but:
North is 0°
Est is 90°
Sud is 180°
West is 270°

**Comment by JTrotta** [comment]
You should change the row 202:  `degree = (degree > 0 ? 360 : 0) - degree;`
into: `degree = (degree + 450) % 360;`

**Comment by dondido** [comment]
![2ebf88dc-54bc-11e5-99f7-2a6e2b7a9926 1](https://github.com/user-attachments/assets/3bcce93a-b7dd-477e-9bb5-6da8631ba92c)

This component was developed as a simplistic alternative to https://www.npmjs.com/package/nipplejs
